env: false
migrate_db: true
version: v1
app:
  port: 8888
mysql:
  name: nomal
  host: 127.0.0.1
  port: 3306
  user: root
  password: mysql
log:
  path: ./logs/
  access_name: access.log
  error_name: error.log
  error_level: debug
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 1
  dialTimeOut: 1
  readTimeOut: 1
  writeTimeOut: 1
  poolTimeOut: 1
  poolSize: 100
email:
  host: smtp.qq.com
  account: xxx@qq.com
  port: 465
  password: xxxxx
